'use strict';
const SOURCES={route:['黒龍までの特別任務・対策','https://game8.jp/mhw/347971','Game8 / 解放順と戦闘準備'],official:['ミラボレアスの特別任務','https://game.capcom.com/manual/MHW_PC/ja/steam/page/16/6','CAPCOM公式マニュアル / MR24・前提任務'],temporal:['転身の装衣：通常版と改','https://game8.jp/mhw/221037','Game8 / 取得経路・改はMR150'],rocksteady:['不動の装衣：取得と危険性','https://game8.jp/mhw/198428','Game8 / HR50・歴戦条件'],aug:['カスタム強化の素材','https://game8.jp/mhw/292922','Game8 / 武器レア度別の素材'],deco:['装飾品の集め方','https://game8.jp/mhw/200233','Game8 / 周回と入手手段'],brachy:['猛り爆ぜるブラキディオス','https://game8.jp/mhw/319317','Game8 / 装備強化の寄り道'],frost:['氷刃佩くベリオロス','https://game8.jp/mhw/341372','Game8 / 氷武器の準備候補'],craig:['Craig：録音仕様','https://craig.chat/','公式 / 話者別・6時間・7日保存'],transcript:['Craig：文字起こし','https://docs.craig.chat/features/transcription/','公式 / Tier 3・TXT / SRT / WebVTT']};
const NODES=[
{id:0,name:'導きの地',short:'遠征のはじまり',icon:'camp',x:105,y:440,quest:'エンディング後の探索',desc:'ここが現在の出発点。まず拠点の会話を進め、追加の特別任務を確認。全地帯のレベル上げや全フリークエスト制覇を、次へ進む条件にはしません。',warn:'所持装衣・正確なMR・防具は未確認。確認しながら荷造りを埋めよう。',source:'route'},
{id:1,name:'溶岩地帯',short:'追加任務を開く',icon:'volcano',x:330,y:458,quest:'キリン → ラージャンの特別任務系列',desc:'「銀色の矜持」から追加任務を進め、導きの地に溶岩地帯を開く。拠点の依頼会話も確認し、次のジンオウガ亜種の調査へ。',warn:'この駒は「地帯が開いた」を記録。ラージャン討伐済みとは同義ではありません。',source:'route'},
{id:2,name:'ジンオウガ亜種',short:'氷雪を越える',icon:'ice',x:550,y:443,quest:'特別任務「失われた幽世線」',desc:'ジンオウガ亜種の特別任務をクリア。氷雪地帯の調査を進め、ムフェト・ジーヴァの偵察任務へつなぐ。',warn:'同行者がクリア済みでも、各自の特別任務の進行を確認する。',source:'route'},
{id:3,name:'ムフェト偵察',short:'未知を調べる',icon:'crystal',x:785,y:418,quest:'偵察任務「戻らずの底」',desc:'偵察任務を終えたら、セリエナの3期団の期団長へ。次のアルバトリオン調査を開く。',warn:'必要なのは「偵察」。ムフェトの本番の討伐周回や覚醒武器厳選は、解放の必須条件ではありません。',source:'route'},
{id:4,name:'アルバ調査',short:'前提任務を出す',icon:'eye',x:848,y:236,quest:'通常のアルバトリオン任務を発生',desc:'通常のアルバ任務を発生させ、必要な調査・会話を進める。陽気な推薦組から、黒龍へ続く「暁の凱還」を受ける。',warn:'通常のアルバ討伐を必須チェックにしない。「暁の凱還」の討伐とは別です。',source:'route'},
{id:5,name:'暁の凱還',short:'黒龍への前哨戦',icon:'dawn',x:615,y:251,quest:'前提任務のアルバトリオンを討伐',desc:'「暁の凱還」をクリアし、会話を進めて「黒龍ミラボレアス」を発生させる。受注条件はMR24以上。',warn:'装備準備と解放は別。アルバ用の属性対策は、黒龍用の物理火力装備と分けて考える。',source:'official'},
{id:6,name:'黒龍に到達',short:'城門の前で',icon:'gate',x:372,y:247,quest:'特別任務「黒龍ミラボレアス」',desc:'ついに黒龍の任務へ。「到達した」と「他の人と共闘できる」は分けて記録。初回の単独パートを進め、マルチプレイが可能になったかゲーム内で確認する。',warn:'serket・zushiの初期位置。共闘解放・討伐経験はまだ未確認です。',source:'route'},
{id:7,name:'共闘解放',short:'四人の一歩を合わせる',icon:'party',x:380,y:90,quest:'各自が初回の単独パートを突破',desc:'共闘できることを確認したら、役割を合わせて黒龍へ。まずは生存、頭の部位破壊、兵器の担当を相談する。',warn:'砲撃手は兵器担当に。全員が同じサポート構成である必要はありません。',source:'route'},
{id:8,name:'黒龍を討つ',short:'その先を、四人で。',icon:'castle',x:690,y:100,quest:'ミラボレアス討伐',desc:'この地点は選択中のハンター本人の討伐記録。四人での討伐は、下の「四人での討伐を記録」で別に残す。',warn:'到達だけで討伐済みにしない。戦果は確認してから記す。',source:'route'}];
const PREP=[
{id:'survival',cat:'base',name:'体力増強3・防具の強化',priority:'最初に確認',desc:'まず現在の防具を強化できるところまで強化し、体力増強Lv3など生存の土台を整える。装備画面があれば無理なく差し替える部位を選べる。防具のカスタム強化は別段階。',source:'route',from:0},
{id:'supply',cat:'base',name:'補給・植生研究所・調合',priority:'毎回の狩りが楽',desc:'植生研究所の栽培枠・肥料、よく使うキャンプ、食事と補給を確認。秘薬などの調合・アイテムマイセットを整える。全てを埋めず、普段足りなくなる消耗品に関わる依頼を優先する案。',source:'',from:0},
{id:'temporal',cat:'mantle',name:'転身の装衣〈通常版〉',priority:'優先候補',desc:'ソードマスターの会話から「烈日」→「パンドラの闘技場」→「平伏するより他に無し」。最後に会話して受け取る。「改」はMR150なので今は待たなくてよい。小さい被弾や継続ダメージは防げない。',source:'temporal',from:0},
{id:'rocksteady',cat:'mantle',name:'不動の装衣〈通常版〉',priority:'スラアクの候補',desc:'HR50以降、危険度3の歴戦を3種類狩猟し、武具屋の依頼「奈落にて君を喚ぶ」へ。不動は連続被弾で急に倒れる危険もある。持っていないこと自体を黒龍解放のブロックにはしない。',source:'rocksteady',from:0},
{id:'mantle-up',cat:'mantle',name:'装衣の強化は必要分だけ',priority:'任意',desc:'スロットを増やす「改」は、元の装衣取得とは別。転身・改を待つためにMR150まで上げる必要はない。不動・改は、元の装衣所持＋MR17以上で「舞踏家たちのドゥエート」「捕獲：雷の顎を捕まえろ！」を済ませ、武具屋から「黒炯々」へ。',source:'rocksteady',from:0},
{id:'jewels',cat:'gear',name:'必要な珠を絞って集める',priority:'理想の珠待ちをしない',desc:'まず手持ちと足りないスキルを照合。マカ錬金で直接作れる珠と、抽選で狙う珠は別。MR24から「鳴神上狼、荒事を成す」、MR100以降は「滅日」が周回候補。理想の珠が出るまで任務を止めず、不要分だけを錬金に回す。',source:'deco',from:0},
{id:'weapon',cat:'gear',name:'主力武器とスキルの棚卸し',priority:'本人の構成で判断',desc:'武器名・防具5部位・護石・発動スキルを確認し、スラアク、片手、ヘビィなど実際の用途に合わせて選ぶ。全員に同じ珠や装備を押しつけない。支援役も攻撃参加できる余地を残す。',source:'',from:0},
{id:'brachy',cat:'gear',name:'臨界ブラキの装備を検討',priority:'強化の寄り道',desc:'猛り爆ぜるブラキディオスの武器・防具は、主力強化の候補。特別任務を開いて必要素材を集める。ただしこの討伐そのものは、黒龍の解放条件ではない。所有装備との差を見て選ぶ。',source:'brachy',from:1},
{id:'element',cat:'gear',name:'アルバ用の属性装備',priority:'アルバ前に',desc:'黒龍を目指す装備とアルバの属性対策は別枠にする。氷刃佩くベリオロスの氷武器など、主力武器で作れる属性装備を検討。必要チケットを落とすクエストをゲーム内報酬・攻略資料で確認する。',source:'frost',from:3},
{id:'aug12',cat:'augment',name:'レア12武器の回復カスタム',priority:'安定を目指す道',desc:'MR100・導きの地の陸珊瑚Lv7で歴戦ネロミェール素材を狙う段階が目標。攻撃しながら回復したい近接の強化候補。全武器がMR100必須という意味ではなく、レア度やカスタム種別で素材が異なる。',source:'aug',from:6,mr:100},
{id:'fatalis-kit',cat:'base',name:'黒龍用の生存・部位破壊',priority:'黒龍前に',desc:'頭破壊を助ける構成、避難場所、回復と補給を確認。耐熱の装衣なども候補。不動で攻撃を受け続けるのではなく、生きて手数を出せる構成を選ぶ。',source:'route',from:5},
{id:'artillery',cat:'base',name:'兵器担当と頭破壊を相談',priority:'共闘前に',desc:'砲撃手Lv2を持つ兵器担当を決め、拘束中やダウン中に頭へ攻撃を合わせる。最初から全員に役割を固定せず、プレイ後の振り返りで調整する案。',source:'route',from:6}
];
const PEOPLE=[{id:'osakenpiro',mark:'O',color:'#d591aa',seed:0},{id:'keuita',mark:'K',color:'#d6dce3',seed:0},{id:'serket',mark:'S',color:'#8ebbb2',seed:6},{id:'zushi',mark:'Z',color:'#ddac77',seed:6}];
const LABELS={unknown:'？ 未確認',missing:'○ これから',done:'✓ 完了',skip:'− 今は見送り'};
const KEY='mh-fatalis-roadmap:v1',SCHEMA='mh-fatalis-roadmap/v1';
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const seed=()=>({schema:SCHEMA,updatedAt:'2026-09-20',partyClear:false,players:Object.fromEntries(PEOPLE.map(p=>[p.id,{stage:p.seed,mr:null,prep:Object.fromEntries(PREP.map(t=>[t.id,'unknown']))}]))});
let state=seed(),selected=new URLSearchParams(location.search).get('hunter')||'osakenpiro',node=1,filter='now',undoState=null,pending=null,toastTimer=null,storageOk=true;
if(!PEOPLE.some(p=>p.id===selected))selected='osakenpiro';
function validate(raw){if(!raw||raw.schema!==SCHEMA||typeof raw.partyClear!=='boolean'||!raw.players)throw Error('進行データの形式が違います。');const clean=seed();for(const p of PEOPLE){const v=raw.players[p.id];if(!v||!Number.isInteger(v.stage)||v.stage<0||v.stage>8||!(v.mr===null||Number.isInteger(v.mr)&&v.mr>=24&&v.mr<=999))throw Error(p.id+' の地点またはMRが不正です。');const prep={};for(const t of PREP){const value=v.prep?.[t.id]??'unknown';if(!Object.hasOwn(LABELS,value))throw Error('準備の値が不正です。');prep[t.id]=value;}clean.players[p.id]={stage:v.stage,mr:v.mr,prep};}clean.partyClear=raw.partyClear;if(clean.partyClear&&PEOPLE.some(p=>clean.players[p.id].stage!==8))throw Error('四人討伐と各人の地点が矛盾しています。');clean.updatedAt=typeof raw.updatedAt==='string'?raw.updatedAt.slice(0,40):'';return clean;}
try{const raw=localStorage.getItem(KEY);if(raw)state=validate(JSON.parse(raw));}catch(e){storageOk=false;}
node=Math.min(state.players[selected].stage+1,8);
function toast(text){$('toast').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').textContent='',4500);}
function save(){state.updatedAt=new Date().toISOString();try{localStorage.setItem(KEY,JSON.stringify(state));storageOk=true;}catch{storageOk=false;}renderSave();}
function renderSave(){$('save-status').textContent=storageOk?'このブラウザに保存 · 共有にはリンクかJSONを使用':'端末保存を利用できません。閉じる前にJSONを保存してください。';}
function mutate(fn){undoState=structuredClone(state);fn();save();render();}
function dialog(title,text,action,preview=''){pending=action;$('dialog-title').textContent=title;$('dialog-text').textContent=text;$('dialog-preview').textContent=preview;$('dialog-preview').hidden=!preview;$('dialog-input').hidden=true;$('dialog-input').value='';$('dialog-confirm').hidden=!action;$('dialog-confirm').textContent='反映する';$('dialog-cancel').textContent=action?'キャンセル':'閉じる';if(!$('confirm-dialog').open)$('confirm-dialog').showModal();}
$('dialog-cancel').onclick=()=>$('confirm-dialog').close();$('dialog-confirm').onclick=()=>{const action=pending;$('confirm-dialog').close();if(action)action();};
function selectHunter(id){selected=id;node=Math.min(state.players[id].stage+1,8);render();focusMap(state.players[id].stage);}
let overview=false;
function resizeOverview(){if(overview){const map=$('map');map.style.minWidth='1000px';map.style.width='1000px';map.style.zoom=String($('map-viewport').clientWidth/1000);}else{$('map').style.minWidth='';$('map').style.width='';$('map').style.zoom='';}}
$('overview').onclick=()=>{overview=!overview;resizeOverview();$('overview').textContent=overview?'拡大表示':'全体図';};window.addEventListener('resize',resizeOverview);
function focusMap(n){if(overview)return;const view=$('map-viewport'),map=$('map');view.scrollTo({left:Math.max(0,NODES[n].x/1000*map.clientWidth-view.clientWidth/2),behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});}
function nodeDetail(){const n=NODES[node],current=state.players[selected].stage;$('node-eyebrow').textContent=(node===current?'現在地':node===current+1?'次の節目':node<current?'通過した節目':'これからの節目')+' / '+String(node+1).padStart(2,'0');$('node-title').textContent=n.name;$('node-quest').textContent=n.quest;$('node-description').textContent=n.desc;$('node-warning').textContent=n.warn;$('node-source').href=SOURCES[n.source][1];$('node-select').value=node;$('record-node').disabled=node===current;$('record-node').textContent=node===current?'ここが現在地':node<current?'記録をこの地点に訂正する':'ここまで到達したと記録';document.querySelectorAll('.milestone').forEach((el,i)=>{el.setAttribute('aria-pressed',i===node);el.classList.toggle('passed',i<=current);});}
function moveRequest(id,n){const before=state.players[id].stage;if(before===n)return;dialog(id+' の駒を動かす',NODES[before].name+' → '+NODES[n].name+'\nゲーム内で到達を確認した地点を記録します。準備の完了状態は変えません。'+(n<before?'\n前の地点に戻す訂正です。':''),()=>{selected=id;node=n;mutate(()=>{state.players[id].stage=n;if(n<8)state.partyClear=false;});focusMap(n);toast(id+'：'+NODES[n].name+' に記録しました。');});}
function buildMap(){$('node-select').innerHTML=NODES.map(n=>'<option value="'+n.id+'">'+(n.id+1)+'. '+n.name+'</option>').join('');$('milestones').innerHTML=NODES.map(n=>'<button class="milestone '+(n.id===8?'goal':'')+'" style="left:'+n.x/10+'%;top:'+n.y/6.2+'%" data-node="'+n.id+'" aria-label="'+n.name+'の説明"><span class="stone"><svg aria-hidden="true"><use href="#i-'+n.icon+'"/></svg></span><span class="num">'+(n.id+1)+'</span><strong>'+n.name+'</strong><small>'+n.short+'</small></button>').join('');$('pawns').innerHTML=PEOPLE.map(p=>'<button class="pawn" id="pawn-'+p.id+'" style="--player:'+p.color+'" draggable="true" data-person="'+p.id+'"><span>'+p.mark+'</span></button>').join('');document.querySelectorAll('.milestone').forEach(el=>{el.onclick=()=>{node=Number(el.dataset.node);nodeDetail();};el.ondragover=e=>{e.preventDefault();el.classList.add('dragover');};el.ondragleave=()=>el.classList.remove('dragover');el.ondrop=e=>{e.preventDefault();el.classList.remove('dragover');const id=e.dataTransfer.getData('text/plain');if(PEOPLE.some(p=>p.id===id))moveRequest(id,Number(el.dataset.node));};});document.querySelectorAll('.pawn').forEach(el=>{el.onclick=()=>selectHunter(el.dataset.person);el.ondragstart=e=>e.dataTransfer.setData('text/plain',el.dataset.person);});}
function renderRoster(){$('roster').innerHTML=PEOPLE.map(p=>{const v=state.players[p.id];return '<button class="hunter" style="--player:'+p.color+'" aria-pressed="'+(p.id===selected)+'" data-hunter="'+p.id+'"><span class="player-chip">'+p.mark+'</span><span><span class="name">'+p.id+'</span><span class="sub">'+NODES[v.stage].name+(v.mr?' · MR '+v.mr:'')+'</span></span></button>';}).join('');document.querySelectorAll('[data-hunter]').forEach(el=>el.onclick=()=>selectHunter(el.dataset.hunter));$('selected-caption').textContent=selected+' の遠征図';for(const p of PEOPLE){const n=state.players[p.id].stage,same=PEOPLE.filter(q=>state.players[q.id].stage===n),index=same.indexOf(p),x=NODES[n].x+(index-(same.length-1)/2)*32,el=$('pawn-'+p.id);el.style.left=x/10+'%';el.style.top=(NODES[n].y-35)/6.2+'%';el.setAttribute('aria-pressed',p.id===selected);el.setAttribute('aria-label',p.id+'：'+NODES[n].name+'。選択して地点を変更');el.title=p.id+' / '+NODES[n].name;}}
const FILTERS=[['now','いま確認'],['base','補給・連携'],['mantle','装衣'],['gear','装備・珠'],['augment','MR強化'],['all','全部']];
function renderPrep(){const v=state.players[selected],done=Object.values(v.prep).filter(x=>x==='done').length;$('prep-caption').textContent=selected+' · 確認済みの完了 '+done+' / '+PREP.length+'項目（解放率ではありません）';$('mr-input').value=v.mr??'';$('filter-bar').innerHTML=FILTERS.map(([id,text])=>'<button data-prep-filter="'+id+'" aria-pressed="'+(id===filter)+'">'+text+'</button>').join('');document.querySelectorAll('[data-prep-filter]').forEach(el=>el.onclick=()=>{filter=el.dataset.prepFilter;renderPrep();});const tasks=PREP.filter(t=>filter==='all'||filter==='now'&&t.from<=v.stage&&v.prep[t.id]!=='done'&&v.prep[t.id]!=='skip'||filter===t.cat);$('ledger').innerHTML=tasks.length?tasks.map(t=>'<div class="prep-row" data-status="'+v.prep[t.id]+'"><label><span class="sr-only">'+t.name+'の状態</span><select data-prep="'+t.id+'">'+Object.entries(LABELS).map(([value,label])=>'<option value="'+value+'"'+(value===v.prep[t.id]?' selected':'')+'>'+label+'</option>').join('')+'</select></label><details><summary><span><span class="prep-name">'+t.name+'</span><span class="prep-priority">'+t.priority+'</span></span></summary><p>'+t.desc+'</p>'+(t.source?'<a href="'+SOURCES[t.source][1]+'" target="_blank" rel="noopener noreferrer">出典：'+SOURCES[t.source][0]+' ↗</a>':'<span class="small muted">このパーティ向けの運用提案</span>')+'</details>'+(t.mr&&(!v.mr||v.mr<t.mr)?'<span></span><span class="prepgate">'+(v.mr?'MR'+t.mr+'以降の強化候補':'MR未確認 · MR'+t.mr+'以降の強化候補')+'</span>':'')+'</div>').join(''):'<p class="notice">この絞り込みでは、残りの確認項目はありません。</p>';document.querySelectorAll('[data-prep]').forEach(el=>el.onchange=()=>{const value=el.value,id=el.dataset.prep;mutate(()=>state.players[selected].prep[id]=value);toast('準備を更新しました。');});}
function renderNext(){const v=state.players[selected],n=NODES[Math.min(v.stage+1,8)],unknown=PREP.filter(t=>t.from<=v.stage&&v.prep[t.id]==='unknown');let items=[[v.stage<8?'解放を一つ先へ':'次の目標を相談',v.stage<8?n.quest:'討伐後の目標を相談。四人討伐の記録は別に残す。'],[unknown.length?'持ち物を確認する':'不足分を絞る',unknown.length?unknown.slice(0,2).map(t=>t.name).join('・')+'。未確認を未所持と決めつけない。':'「これから」の項目から必要なものだけを選ぶ。'],['同行者と合わせる',v.stage<6?'serket・zushiと、任務解放や必要素材の狩りを相談。':'初回単独パートの通過状況を確認。兵器と頭破壊の役割を相談。']];$('next-actions').innerHTML=items.map(([title,text],i)=>'<div class="next-action"><b>'+String(i+1).padStart(2,'0')+'</b><strong>'+title+'</strong><p>'+text+'</p></div>').join('');}
function render(){renderRoster();nodeDetail();renderPrep();renderNext();renderSave();$('undo').disabled=!undoState;$('party-status').textContent=state.partyClear?'✓ 四人での黒龍討伐を記録済み':'四人での討伐：未記録（個人の到達とは別）';$('party-status').classList.toggle('celebrate',state.partyClear);$('party-clear').disabled=state.partyClear;}
$('node-select').onchange=e=>{node=Number(e.target.value);nodeDetail();focusMap(node);};$('record-node').onclick=()=>moveRequest(selected,node);$('focus-next').onclick=()=>{node=Math.min(state.players[selected].stage+1,8);nodeDetail();focusMap(node);};document.querySelectorAll('.camp-stop').forEach(el=>el.onclick=()=>{filter=el.dataset.filter;renderPrep();$('preparations').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});});
$('mr-input').onchange=e=>{const value=e.target.value.trim(),mr=value===''?null:Number(value);if(mr!==null&&(!Number.isInteger(mr)||mr<24||mr>999)){toast('MRは24〜999の整数、未確認は空欄にしてください。');e.target.value=state.players[selected].mr??'';return;}mutate(()=>state.players[selected].mr=mr);};
$('undo').onclick=()=>{if(!undoState)return;state=undoState;undoState=null;node=Math.min(state.players[selected].stage+1,8);save();render();toast('ひとつ前の記録に戻しました。');};
$('party-clear').onclick=()=>dialog('四人で、黒龍を討った。','osakenpiro・keuita・serket・zushiの四人で討伐したことを記録します。全員の駒も「黒龍を討つ」に進めます。実際のクリアを確認してください。',()=>{mutate(()=>{state.partyClear=true;for(const p of PEOPLE)state.players[p.id].stage=8;});node=8;nodeDetail();focusMap(8);toast('四人の戦果を記録しました。お見事！');});
async function copy(text,title='コピー用テキスト'){try{await navigator.clipboard.writeText(text);toast('コピーしました。');}catch{dialog(title,'下の内容を選択してコピーしてください。',null);$('dialog-input').hidden=false;$('dialog-input').value=text;$('dialog-input').readOnly=true;$('dialog-input').focus();$('dialog-input').select();}}
function bytesToBase64(text){let binary='';new TextEncoder().encode(text).forEach(b=>binary+=String.fromCharCode(b));return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function base64ToText(text){if(text.length>30000)throw Error('共有データが長すぎます。');const normalized=text.replace(/-/g,'+').replace(/_/g,'/'),binary=atob(normalized+'='.repeat((4-normalized.length%4)%4));return new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(binary,c=>c.charCodeAt(0)));}
$('share').onclick=()=>{const url=new URL(location.href);url.searchParams.set('hunter',selected);url.hash='party='+bytesToBase64(JSON.stringify(state));dialog('この時点の進行度を共有','リンクには4人の進行度・MR・準備状態が含まれます。リアルタイム同期ではありません。共有してよい内容か確認してください。',()=>copy(url.href,'共有リンク'));$('dialog-confirm').textContent='リンクをコピー';};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='fatalis-party-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);toast('進行度をJSONに保存しました。');};
function summary(data){return PEOPLE.map(p=>p.id+'：'+NODES[data.players[p.id].stage].name+' / MR '+(data.players[p.id].mr??'未確認')).join('\n')+'\n四人討伐：'+(data.partyClear?'記録済み':'未記録');}
function loadData(raw){if(raw?.schema==='mh-fatalis-proposal/v1'){applyProposal(raw);return;}const next=validate(raw);dialog('共有された進行度を取り込む','4人全員の記録をこの内容に置き換えます。古い写しではないか、準備状態も確認してください。\n記録日時：'+(next.updatedAt||'不明'),()=>{mutate(()=>state=next);node=Math.min(state.players[selected].stage+1,8);nodeDetail();toast('進行度を取り込みました。');},summary(next)+'\n\n準備の変更：\n'+PEOPLE.flatMap(p=>PREP.filter(t=>state.players[p.id].prep[t.id]!==next.players[p.id].prep[t.id]).map(t=>p.id+' / '+t.name+'：'+LABELS[state.players[p.id].prep[t.id]]+' → '+LABELS[next.players[p.id].prep[t.id]])).join('\n'));}
$('import').onclick=()=>$('file-import').click();$('file-import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>100000)throw Error('JSONは100KB以下にしてください。');loadData(JSON.parse(await file.text()));}catch(err){toast('取込できません：'+err.message);}finally{e.target.value='';}};
function applyProposal(raw){if(!Array.isArray(raw.updates)||!raw.updates.length||raw.updates.length>30)throw Error('更新案は1〜30件にしてください。');const next=structuredClone(state),review=[];for(const u of raw.updates){if(!PEOPLE.some(p=>p.id===u.hunter))throw Error('未知のハンターです。');if(typeof u.evidence!=='string'||u.evidence.length<2||u.evidence.length>1000)throw Error('更新案には短い根拠が必要です。');const v=next.players[u.hunter];review.push(u.hunter+'\n根拠：'+u.evidence);if(Object.hasOwn(u,'stage')){if(!Number.isInteger(u.stage)||!NODES[u.stage])throw Error('地点IDが不正です。');review.push('地点：'+NODES[v.stage].name+' → '+NODES[u.stage].name);v.stage=u.stage;}if(Object.hasOwn(u,'mr')){if(!(u.mr===null||Number.isInteger(u.mr)&&u.mr>=24&&u.mr<=999))throw Error('MRが不正です。');review.push('MR：'+(v.mr??'未確認')+' → '+(u.mr??'未確認'));v.mr=u.mr;}if(u.prep){if(typeof u.prep!=='object'||Array.isArray(u.prep))throw Error('準備の形式が違います。');for(const [id,status]of Object.entries(u.prep)){const t=PREP.find(t=>t.id===id);if(!t||!Object.hasOwn(LABELS,status))throw Error('未知の準備項目・値です。');review.push(t.name+'：'+LABELS[v.prep[id]]+' → '+LABELS[status]);v.prep[id]=status;}}review.push('');}if(PEOPLE.some(p=>next.players[p.id].stage<8))next.partyClear=false;validate(next);dialog('音声ログからの更新案を確認','これは提案です。発言者・時刻・完了の根拠が正しいか確認してから反映してください。原文は保存されず、進行度だけが残ります。',()=>{mutate(()=>state=next);node=Math.min(state.players[selected].stage+1,8);nodeDetail();toast('確認した更新案を反映しました。');},review.join('\n'));}
$('paste-proposal').onclick=()=>{dialog('更新案JSONを貼り付け','文字起こしから作った更新案を貼り付けてください。次の画面で変更内容を確認します。',()=>{try{const value=$('dialog-input').value;if(value.length>100000)throw Error('JSONが長すぎます。');loadData(JSON.parse(value));}catch(err){toast('取込できません：'+err.message);}});$('dialog-input').hidden=false;$('dialog-input').readOnly=false;$('dialog-input').placeholder='{"schema":"mh-fatalis-proposal/v1","updates":[...]}';$('dialog-confirm').textContent='内容を確認';};
$('copy-brief').onclick=()=>copy('【狩猟引継ぎ】\n'+summary(state)+'\n\n【今日の報告：各自30秒】\n名前／MR／クリアした任務／入手した装衣・装備／困ったこと／次にやりたいこと\n※予定と完了を区別。装備・スキル画面も添付。\n\n【進行度JSON】\n'+JSON.stringify(state));
$('copy-prompt').onclick=()=>copy('モンハンの狩猟VC文字起こしから進行度の更新候補だけを抽出してください。話者はosakenpiro,keuita,serket,zushi。本人の明示的な完了発言と話者・時刻を根拠にし、冗談・予定・推測を完了扱いしないでください。音声だけで断定できない装備は未確認のまま。不明な項目は更新対象に含めないでください。まず人が読める差分を示し、次に下記形式のJSONを出してください。このページでは取込後も人が確認します。\n形式：{"schema":"mh-fatalis-proposal/v1","updates":[{"hunter":"osakenpiro","stage":0,"mr":null,"prep":{"temporal":"done"},"evidence":"時刻・話者・明示された完了根拠"}]}\n上の値は形式例であり、実際の更新指示ではありません。変更がないフィールドは省略。\n地点ID：'+NODES.map(n=>n.id+'='+n.name).join(', ')+'\n準備ID：'+PREP.map(t=>t.id+'='+t.name).join(', ')+'\n準備状態：unknown=未確認, missing=これから, done=完了, skip=見送り。MRは24〜999またはnull。\n現状：'+JSON.stringify(state)+'\n\n【ここに文字起こしを添付】');
$('source-list').innerHTML=Object.values(SOURCES).map(([title,url,desc])=>'<div><a target="_blank" rel="noopener noreferrer" href="'+url+'">'+title+' ↗</a><small>'+desc+'</small></div>').join('');
buildMap();render();
try{if(location.hash.startsWith('#party=')){const raw=JSON.parse(base64ToText(location.hash.slice(7)));loadData(raw);history.replaceState(null,'',location.pathname+location.search);}}catch(err){toast('共有リンクを取り込めません：'+err.message);}
