(()=>{'use strict';
const $=id=>document.getElementById(id),KEY='mh-hunt-flow:v1',SCHEMA='mh-hunt-flow/v1',EKEY='mh-osakenpiro-preparation:v1',PKEY='mh-osakenpiro-compare:v1',BKEY='mh-fatalis-roadmap:v1';
const DKEY='mh-party-departure:v1',SHARE='mh-hunt-flow/v2';
const ELEMENTS={unknown:'未確認',ice:'氷',fire:'火',water:'水',thunder:'雷',dragon:'龍',none:'無属性・状態異常'};
const QUESTS={unknown:'未選択',special:'宵闇の煌黒星',dawn:'暁の凱還',evening:'宵の恒星',morning:'明けの死星'};
const PEOPLE=[['osakenpiro','O','#d591aa'],['keuita','K','#d6dce3'],['serket','S','#8ebbb2'],['zushi','Z','#ddac77']];
const URLS={head:'https://game8.jp/mhw/290180',legs:'https://game8.jp/mhw/290217',kirin:'https://game8.jp/mhw/296975',teo:'https://game8.jp/mhw/289500',armor:'https://game8.jp/mhw/355462',jewels:'https://game8.jp/mhw/322627',frost:'https://gamewith.jp/mhw/213473',geo:'https://game8.jp/mhw/199529',alba:'https://game8.jp/mhw/341351',augment:'https://game8.jp/mhw/292922',safi:'https://gamewith.jp/mhw/179612'};
const TASKS=[
{id:'head',lane:'prep',title:'氷牙竜ベリオロス！',sub:'頭α：回避距離2＋強化持続1',type:'M★3 フリー / MR6以上',source:'head',recipes:['head'],goal:'EXベリオヘルムαを作成、または同じ役割の手持ち装備を確認したら終了。',desc:'まず通常ベリオの頭。アンジャナフ火スラアクを使う練習にもなる。氷刃の素材では、この頭は作れない。',warn:'任務「凍てつく国の白い騎士」クリアで解放。ウルグの厚毛皮はMR小型素材。手持ちで足りるなら周回を省く。',items:[['氷牙竜の厚毛皮',2],['琥珀色の重牙',1],['氷牙竜の重棘',3],['ウルグの厚毛皮',2]]},
{id:'legs',lane:'prep',title:'森に兇爪あり',sub:'脚α：整備2＋強化持続1',type:'M★4 フリー / MR14以上',source:'legs',recipes:['legs'],goal:'EXデスガロングリーヴαを作成、または手持ちの代替装備で役割を確保したら終了。',desc:'オドガロン亜種の脚を作る。頭と脚だけで、回避距離2・強化持続2・整備2まで揃う構成案。',warn:'任務「兇終隙末オドガロン亜種」クリアで解放。通常オドガロンではなく亜種。',items:[['兇爪竜の強硬筋',3],['兇爪竜の厚鱗',2],['兇爪竜の靭尾',1],['強靭な爪',3]]},
{id:'other',lane:'prep',title:'稲光 ／ 砂上にて謁見す',sub:'胴・腰・腕は未所持分だけ',type:'M★5 フリー / MR19以上',source:'kirin',recipes:['chest','waist','arms'],goal:'胴・腰・腕を作るか、代替装備で必要な生存・会心・耐性スキルを確保。',desc:'「稲光」のMRキリンで胴αと腰β、「砂上にて謁見す」のMRテオで腕β。材料が重いなら手持ちを比較してから。',warn:'それぞれMR個体の狩猟で出現するフリー。未解放なら該当MR調査・救難や解放ルートを確認。砕竜の天殻、雷顎竜の天鱗は別個体の素材。護石用の上位テオ素材と混同しない。',items:[['幻獣の銀たてがみ',6],['幻獣の特上皮',3],['幻獣の靭雷尾',3],['砕竜の天殻',1],['炎王龍の重殻',3],['獄炎の厚龍鱗',3],['炎王龍の剛角',1],['雷顎竜の天鱗',1]]},
{id:'armor',lane:'parallel',title:'黒轟竜は傷つかない',sub:'鎧玉 → 加工屋で防具を強化',type:'M★6 イベント / MR24以上',source:'armor',mr:24,goal:'5部位を現在の上限まで強化する分の鎧玉とゼニーを確保。加工屋で強化して区切る。',desc:'鎧玉の周回枠。初戦が厳しければ仲間と行くか、先に所持鎧玉とバウンティで強化する。防御力の数字だけで生存保証はしない。',warn:'相手はティガレックス亜種。火属性は通らないので、火特化を固定しない。地質学でこの報酬の鎧玉が増えるわけではない。',items:[]},
{id:'jewels',lane:'parallel',title:'鳴神上狼、荒事を成す',sub:'不足する珠だけを埋める',type:'M★6 イベント / MR24以上',source:'jewels',mr:24,recipes:['jewels'],goal:'必要な基本スキルが装備全体で揃ったら一区切り。理想の複合珠は挑戦の条件にしない。',desc:'歴戦ジンオウガ。手持ちとマカ錬金の選択肢を先に確認し、足りない珠を狙う周回。氷武器の練習と並行する案。',warn:'このクエストで目当ての珠が確定するわけではない。序盤の防具強化より先に無理な歴戦周回を強制しない。地学珠は報酬増加にはならない。',items:[['体力珠【1】',3],['痛撃珠【2】',2],['昂揚珠【2】',1],['整備珠【1】',1],['耐属珠【1】',1]]},
{id:'weapon',lane:'parallel',title:'加工屋 → 氷の支度を確認',sub:'本命：ゴアフロストオラリア＋氷結Ⅲ',type:'画像の氷構成を制作 / 不足時のみ「終の白騎士」',source:'frost',goal:'氷の最終武器・氷結の護石Ⅲ・氷結珠3個を確認。火セットの完成は本命フローに要求しない。',desc:'本人選択：画像の氷構成が制作本命。氷刃素材あり、アンジャナフ火スラアクは作成済み。まず加工屋で所持素材を確認し、不足時だけ「終の白騎士」（MR24以上）へ。火の比較票は残す。',warn:'炎活性開始の初回・暁の凱還には氷。氷活性開始の明けの死星には火。制作目標を採用しただけでは最終武器の所持・完成を確定しない。',items:[]},
{id:'trial',lane:'trial',title:'生産武器で、アルバを試す',sub:'解放任務＋対応属性＋生存を確認して出発',type:'アルバトリオン / クエスト名と開始属性を確認',source:'alba',goal:'属性抑制・角破壊・生存のどこが不足かを確認して振り返る。このチェックは討伐済みの記録ではない。',desc:'武器が揃っても特別任務の解放は別。四人の進行ボードの前提任務を確認。ムフェト偵察は解放ルートに含むが、討伐周回と覚醒武器厳選は別。',warn:'導き用に耐属珠を地学珠へ替えた場合は戻す。負けたら即ムフェト周回ではなく、属性の選択・龍やられ・被弾・狙い所を見直す。',items:[]},
{id:'guiding',lane:'optional',title:'導きの地で回復カスタム',sub:'火MR50 → 氷MR70 → R12はMR100',type:'並行する強化 / 地学珠の出番',source:'augment',goal:'自分のMRと武器レア度に合う回復能力付与Ⅰを加工屋で付けたら、その段階は終了。',desc:'R10火は瘴気Lv5、R11氷は森林Lv6、R12は陸珊瑚Lv7が目標。MR上限解放任務も必要。手元のMRは未確認なら先の歴戦個体を今の周回先にしない。',warn:'導きの対象落とし物は地質学1で2回拾える。すべての落とし物やイベクエ報酬には効かない。回復は命中補助・無敵ではない。材料詳細は素材帳の回復タブ。',items:[]},
{id:'safi',lane:'optional',title:'ムフェト周回を再検討',sub:'不足を見て選ぶ。今回の必須宿題ではない',type:'任意 / 緊急任務「赤き龍」/ 開催枠未確認',source:'safi',goal:'必要な武器・防具素材を決めて確保したら終了。全属性厳選を強制しない。',desc:'まず手持ちの生産武器を使う方針を維持。強化が必要なら、覚醒武器・防具素材・龍光石を狙う。偵察と本番は別の任務。',warn:'このページは現在の開催日時を確認できていない。集会所の告知で確認。爆破武器はアルバの属性抑制用とは別枠。',items:[]}
];
const IDS=new Set(TASKS.map(t=>t.id)),ACTIVES=new Set(['unknown','frost','kirin','teo',...IDS]);
const ACTIVITY={unknown:'周回先は未確認',frost:'終の白騎士',kirin:'稲光',teo:'砂上にて謁見す'};for(const t of TASKS)ACTIVITY[t.id]=t.title;
function seed(){return{schema:SCHEMA,players:Object.fromEntries(PEOPLE.map(([id])=>[id,{active:'unknown',geology:id==='osakenpiro'?true:null,done:{},updatedAt:id==='osakenpiro'?'2026-09-21':''}]))};}
let model=seed(),who=new URLSearchParams(location.search).get('hunter')||'osakenpiro',view='head',legacy={},plan={},board={},blocked=false,undo=null,action=null,timer=null,localReadErrors=[];
if(!PEOPLE.some(p=>p[0]===who))who='osakenpiro';
function checkRecord(r){if(!r||typeof r!=='object'||Array.isArray(r)||!ACTIVES.has(r.active)||!(r.geology===null||typeof r.geology==='boolean')||!r.done||typeof r.done!=='object'||Array.isArray(r.done))throw Error('現在地の形式が違います。');const out={active:r.active,geology:r.geology,done:{},updatedAt:typeof r.updatedAt==='string'?r.updatedAt.slice(0,40):''};for(const[id,v]of Object.entries(r.done)){if(!IDS.has(id)||typeof v!=='boolean')throw Error('工程の値が不正です。');out.done[id]=v;}return out;}
function validate(raw){if(!raw||![SCHEMA,SHARE].includes(raw.schema)||!raw.players||typeof raw.players!=='object'||Array.isArray(raw.players))throw Error('狩猟フローのJSONではありません。');const out={schema:SCHEMA,players:{}};const entries=Object.entries(raw.players);if(!entries.length||entries.length>4)throw Error('ハンター数が不正です。');for(const[id,r]of entries){if(!PEOPLE.some(p=>p[0]===id))throw Error('未知のハンターです。');out.players[id]=checkRecord(r);}if(raw.departure!==undefined){
 if(raw.schema!==SHARE||!raw.departure||typeof raw.departure!=='object'||!Object.hasOwn(QUESTS,raw.departure.quest)||!raw.departure.players||typeof raw.departure.players!=='object'||Array.isArray(raw.departure.players))throw Error('出発情報の形式が違います。');
 const players={};for(const[id,element]of Object.entries(raw.departure.players)){if(!Object.hasOwn(out.players,id)||!Object.hasOwn(ELEMENTS,element))throw Error('共有対象外のハンター・出発属性です。');players[id]=element;}
 out.departure={quest:raw.departure.quest,players};
 }return out;}
function readDeparture(){const raw=localStorage.getItem(DKEY);if(!raw)return{schema:'mh-party-departure/v1',quest:'unknown',departure:Object.fromEntries(PEOPLE.map(([id])=>[id,'unknown']))};const v=JSON.parse(raw);if(!v||v.schema!=='mh-party-departure/v1'||!Object.hasOwn(QUESTS,v.quest)||!v.departure||typeof v.departure!=='object')throw Error('保存済みの出発メモを読み込めません。上書きせず確認してください。');const out={schema:v.schema,quest:v.quest,departure:{}};for(const[id]of PEOPLE){if(!Object.hasOwn(ELEMENTS,v.departure[id]))throw Error('保存済みの出発属性が不正です。');out.departure[id]=v.departure[id];}return out;}
function restoreRaw(key,raw){if(raw===null)localStorage.removeItem(key);else localStorage.setItem(key,raw);}
function writePair(flow,departure){const beforeFlow=localStorage.getItem(KEY),beforeDeparture=localStorage.getItem(DKEY);try{localStorage.setItem(KEY,JSON.stringify(flow));if(departure!==null)localStorage.setItem(DKEY,JSON.stringify(departure));}catch(error){let rollback=true;try{restoreRaw(KEY,beforeFlow);restoreRaw(DKEY,beforeDeparture);}catch{rollback=false;}if(!rollback)blocked=true;throw Error(rollback?'保存に失敗したため変更を取り消しました。':'保存と巻き戻しに失敗しました。JSONを保存して記録を確認してください。');}return{beforeFlow,beforeDeparture};}
function notifyDeparture(){window.dispatchEvent(new CustomEvent('mh:departure-updated',{detail:{source:'flow'}}));}

function readExternal(){localReadErrors=[];function read(key){try{const raw=localStorage.getItem(key);if(!raw)return{};const value=JSON.parse(raw);if(!value||typeof value!=='object'||Array.isArray(value))throw Error();return value;}catch{localReadErrors.push(key);return{};}}legacy=read(EKEY);plan=read(PKEY);board=read(BKEY);}
try{const s=localStorage.getItem(KEY);if(s){const good=validate(JSON.parse(s));Object.assign(model.players,good.players);}}catch{blocked=true;}
readExternal();
function say(t){$('toast').textContent=t;clearTimeout(timer);timer=setTimeout(()=>$('toast').textContent='',4500);}
function status(){ $('save-status').textContent=blocked?'保存済みフローを読み込めないため上書き停止中。JSON取込で確認して復旧できます。':localReadErrors.length?'一部の旧台帳を読めません。空の状態で上書きせず、フローだけ別保存します。':'端末内保存 / 同期なし / 装備票・素材数は既存の記録を読み取り';}
function save(){if(blocked){say('既存フローを保護して上書きを停止中です。JSONを保存してください。');return;}try{localStorage.setItem(KEY,JSON.stringify(model));}catch{blocked=true;say('保存できません。JSON保存を使ってください。');}status();}
function mutate(fn){undo={model:structuredClone(model)};fn();model.players[who].updatedAt=new Date().toISOString();save();render();}
function mrFor(id){if(id==='osakenpiro'&&Number.isInteger(legacy.mr)&&legacy.mr>=24&&legacy.mr<=999)return legacy.mr;const mr=board.players?.[id]?.mr;return Number.isInteger(mr)&&mr>=24&&mr<=999?mr:null;}
function completion(t,id=who){const own=model.players[id].done;if(Object.hasOwn(own,t.id))return{done:own[t.id],origin:'フローでの本人確認'};if(id!=='osakenpiro')return{done:false,origin:'未確認'};if(t.id==='armor'&&legacy.armorUp===true)return{done:true,origin:'防御記録と連動'};if(t.recipes?.every(k=>plan.done?.[k]===true))return{done:true,origin:'装備票の完了と連動'};if(t.id==='weapon'&&plan.done?.ice===true&&plan.iceCharm===3&&plan.done?.['ice-gems']===true)return{done:true,origin:'本命の氷装備票と連動'};return{done:false,origin:'所持・達成を確認'};}
function nextTask(){if(who!=='osakenpiro')return TASKS.find(t=>t.id===model.players[who].active)||TASKS[0];return TASKS.slice(0,7).find(t=>!completion(t).done)||TASKS[7];}
function showDialog(title,text,fn,preview=''){action=fn;$('adopt-quest-label').hidden=true;$('adopt-quest').checked=false;$('dialog-title').textContent=title;$('dialog-text').textContent=text;$('dialog-preview').hidden=!preview;$('dialog-preview').textContent=preview;$('dialog-copy').hidden=true;$('confirm').hidden=!fn;$('confirm').textContent='反映する';$('cancel').textContent=fn?'キャンセル':'閉じる';if(!$('dialog').open)$('dialog').showModal();}
$('cancel').onclick=()=>$('dialog').close();$('confirm').onclick=()=>{const f=action;$('dialog').close();if(f)f();};
let geologyEdited=false;
$('geology').addEventListener('change',()=>{geologyEdited=true;});
function setActive(id){const person=who,geo=geologyEdited?$('geology').checked:model.players[person].geology;showDialog(person+' の現在地','「'+ACTIVITY[id]+'」を今の活動として記録します。工程完了や四人の大目標の駒は動かしません。',()=>mutate(()=>{model.players[person].active=id;model.players[person].geology=geo;geologyEdited=false;}));}

function renderRoster(){ $('roster').replaceChildren(...PEOPLE.map(([id,mark,color])=>{const b=document.createElement('button');b.className='person';b.style.setProperty('--p',color);b.setAttribute('aria-pressed',id===who);const chip=document.createElement('b');chip.textContent=mark;const text=document.createElement('span'),name=document.createElement('strong'),sub=document.createElement('small');name.textContent=id;sub.textContent=model.players[id].active==='unknown'?(id==='osakenpiro'&&model.players[id].geology?'地学珠で周回中・任務未確認':'活動未確認'):ACTIVITY[model.players[id].active];text.append(name,sub);b.append(chip,text);b.onclick=()=>{who=id;geologyEdited=false;view=nextTask().id;try{const u=new URL(location.href);u.searchParams.set('hunter',id);history.replaceState(null,'',u.href);}catch{}render();};return b;}));}
function renderCurrent(){const r=model.players[who];$('hunter-name').textContent=who;$('current-title').textContent=r.active==='unknown'?(who==='osakenpiro'&&r.geology?'地学珠をつけて、周回中。':'現在のクエストは未確認。'):ACTIVITY[r.active];$('current-note').textContent=r.active==='unknown'?'本人申告の範囲だけ表示。クエスト名を選ぶと、フローに現在地が付きます。':'活動の記録：'+(r.updatedAt||'日時未記録')+'。周回中と目標達成は別です。';$('active-select').replaceChildren(...[...ACTIVES].map(id=>{const o=document.createElement('option');o.value=id;o.textContent=ACTIVITY[id];return o;}));$('active-select').value=r.active;$('geology').checked=r.geology===true;$('geology').indeterminate=r.geology===null;$('geo-hint').textContent=r.geology?(r.active==='guiding'?'導きの対象落とし物：地質学1の対象。通常素材と導き素材を分けて拾う。':'地学珠を使用中。導きの対象落とし物には有効、通常イベクエの報酬を増やす効果ではありません。'):'地学珠の有無は、ここから本人が記録できます。';const mr=mrFor(who);$('rank-info').textContent='MR '+(mr??'未確認')+' / 回復カスタムの先行ゲート：50 → 70 → 100';const next=nextTask();$('next-title').textContent=who==='osakenpiro'?next.title:'各自の目標を選んで、現在地を登録';$('next-note').textContent=who==='osakenpiro'?completion(next).done?'必要なら次の強化を選ぶ。':'必要なものが未確認。作成・代替で揃っていればスキップ。':'下の装備ルートはosakenpiro向けの標本。他の人に同じ装備を要求しません。';$('chart-caption').textContent=who==='osakenpiro'?'01 / 必要な防具だけ作る':'クエスト共通カタログ / 装備目標はosakenpiroの参考例';}
function renderChart(){for(const lane of ['prep','parallel','trial','optional']){$('lane-'+lane).replaceChildren(...TASKS.filter(t=>t.lane===lane).map((t,i)=>{const b=document.createElement('button');b.className='task'+(lane==='optional'?' optional':'')+(completion(t).done?' done':'')+((model.players[who].active===t.id||t.id==='other'&&['kirin','teo'].includes(model.players[who].active)||t.id==='weapon'&&model.players[who].active==='frost')?' active':'');b.dataset.task=t.id;b.id='task-'+t.id;b.setAttribute('aria-pressed',t.id===view);const tag=document.createElement('span'),name=document.createElement('strong'),sub=document.createElement('small'),state=document.createElement('span');tag.className='tag';tag.textContent=lane==='prep'?'防具 '+(i+1):lane==='parallel'?'並行 '+(i+1):lane==='trial'?'合流点':'任意の強化';name.textContent=t.title;sub.textContent=t.sub;state.className='state';state.textContent=completion(t).done?'✓ 準備済み · '+completion(t).origin:'○ '+(t.id==='weapon'&&who==='osakenpiro'?'氷の制作本命 · 最終段階未確認':'未確認 → 詳細へ');b.append(tag,name,sub,state);b.onclick=()=>{view=t.id;renderChart();renderDetail();if(innerWidth<=840)$('detail-title').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'center'});};return b;}));}requestAnimationFrame(drawLines);}
function drawLines(){const box=$('chart'),rect=box.getBoundingClientRect(),svg=$('lines');svg.replaceChildren();svg.setAttribute('viewBox',`0 0 ${rect.width} ${rect.height}`);const NS='http://www.w3.org/2000/svg';const edges=[['head','armor'],['legs','jewels'],['other','weapon'],['armor','trial'],['jewels','trial'],['weapon','trial'],['trial','guiding'],['trial','safi']];for(const[a,b]of edges){const x=$('task-'+a).getBoundingClientRect(),y=$('task-'+b).getBoundingClientRect();const sx=x.left+x.width/2-rect.left,sy=x.bottom-rect.top,tx=y.left+y.width/2-rect.left,ty=y.top-rect.top;const p=document.createElementNS(NS,'path');const mid=(sy+ty)/2;p.setAttribute('d',`M${sx},${sy} C${sx},${mid} ${tx},${mid} ${tx},${ty}`);p.setAttribute('fill','none');p.setAttribute('stroke','#cab47b');p.setAttribute('stroke-width','1.5');if(a==='trial')p.setAttribute('stroke-dasharray','4 5');svg.append(p);}}
function renderDetail(){const t=TASKS.find(t=>t.id===view);$('detail-type').textContent=t.type;$('detail-title').textContent=t.title;$('detail-desc').textContent=t.desc;$('detail-stop').textContent=who==='osakenpiro'?t.goal:'このクエストで集めたいものを決めて周回。下の具体的装備・個数はosakenpiroの参考計画で、あなたの必要数ではありません。';$('detail-warning').textContent=t.warn;$('detail-source').href=URLS[t.source];$('unlock-link').href='./?hunter='+encodeURIComponent(who);$('doing').textContent=model.players[who].active===t.id?'ここを周回中と記録済み':'ここを周回中にする';$('doing').disabled=model.players[who].active===t.id;$('complete').disabled=completion(t).done;$('uncomplete').hidden=!completion(t).done;$('detail-status').textContent=completion(t).done?'✓ '+completion(t).origin:'未確認を「未所持」と決めつけず、素材帳を確認してから周回。';const body=$('needs').tBodies[0];body.replaceChildren();$('needs').hidden=!t.items.length||who!=='osakenpiro';if(who==='osakenpiro')for(const[name,qty]of t.items){const row=document.createElement('tr'),n=document.createElement('td'),q=document.createElement('td');n.textContent=name+' ×'+qty;const v=legacy.inventory?.[name];q.textContent=Number.isInteger(v)&&v>=0?'不足 '+Math.max(0,qty-v):'手持ち未確認';row.append(n,q);body.append(row);}$('open-materials').disabled=who!=='osakenpiro';}
function renderMatches(){const map=new Map();for(const[id,r]of Object.entries(model.players)){if(!['head','legs','armor','jewels','frost','kirin','teo','safi'].includes(r.active))continue;const key=r.active;if(!map.has(key))map.set(key,[]);map.get(key).push(id);}const matches=[...map].filter(([,people])=>people.length>=2);$('matches').replaceChildren();if(!matches.length){const p=document.createElement('p');p.className='notice';p.textContent='合流候補はまだありません。未登録の人の行動を推測しません。';$('matches').append(p);}for(const[key,people]of matches){const p=document.createElement('div');p.className='merge-row';const strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=ACTIVITY[key];small.textContent=people.join(' ＋ ')+' · 同じ活動IDの登録。受注条件・地帯Lv・参加可否は各自確認。';p.append(strong,small);$('matches').append(p);}$('party-brief').replaceChildren(...PEOPLE.map(([id])=>{const p=document.createElement('div');p.className='merge-row';const r=model.players[id];p.textContent=id+'：'+ACTIVITY[r.active];return p;}));}
function render(){renderRoster();renderCurrent();renderChart();renderDetail();renderMatches();status();$('undo').disabled=!undo;}
function openEquipment(){if(who!=='osakenpiro'){say('この装備台帳はosakenpiro専用です。');return;}$('equipment').open=true;loadFrame();$('equipment').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});}
function loadFrame(){if(!$('equipment-frame').getAttribute('src'))$('equipment-frame').src='./osakenpiro.html?v=3#materials';}
$('equipment').ontoggle=()=>{if($('equipment').open)loadFrame();};$('open-materials').onclick=openEquipment;$('refresh').onclick=()=>{readExternal();render();say('同じブラウザの素材・装備記録を読み直しました。');};$('set-active').onclick=()=>setActive($('active-select').value);$('doing').onclick=()=>setActive(view);$('next-focus').onclick=()=>{view=nextTask().id;renderChart();renderDetail();$('task-'+view).scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'center'});};
$('complete').onclick=()=>{const t=TASKS.find(t=>t.id===view);showDialog('この工程の目標達成を記録',t.goal+'\n討伐1回の記録とは違います。装備票の所持数や四人の大目標は書き換えません。',()=>mutate(()=>model.players[who].done[view]=true));};
$('uncomplete').onclick=()=>showDialog('フローを未確認に戻す','台帳側の完了記録は消しません。フロー側ではこの工程を再確認対象に戻します。',()=>mutate(()=>model.players[who].done[view]=false));
$('undo').onclick=()=>{if(!undo)return;const old=undo;try{let dep=null;if(Object.hasOwn(old,'departureRaw')){if(localStorage.getItem(DKEY)!==old.departureAfter)throw Error('出発メモが後から変更されています。古い状態へ戻さず確認してください。');dep=old.departureRaw===null?{schema:'mh-party-departure/v1',quest:'unknown',departure:Object.fromEntries(PEOPLE.map(([id])=>[id,'unknown']))}:JSON.parse(old.departureRaw);}writePair(old.model,dep);if(Object.hasOwn(old,'departureRaw')&&old.departureRaw===null)localStorage.removeItem(DKEY);model=old.model;undo=null;notifyDeparture();render();say('確認した更新をひとつ前に戻しました。');}catch(error){say(error.message);}};
async function copy(text){try{await navigator.clipboard.writeText(text);say('コピーしました。');}catch{showDialog('コピー用テキスト','下の内容を選択してコピーしてください。',null);$('dialog-copy').hidden=false;$('dialog-copy').value=text;$('dialog-copy').focus();$('dialog-copy').select();}}
function publicURL(){const u=new URL('https://osakenpiro.github.io/shuryo-techo/fatalis-roadmap/flow.html');u.search='?v=6';u.searchParams.set('hunter',who);return u.href;}
$('copy-update').onclick=()=>copy('狩猟ページを更新した！\n現在地と次の周回フローを先に見られる配置に整理。氷・火の装備比較と素材帳は残しています。\n現在地リンクには、本人が記録した出発属性も含めて共有できるようにしました。取り込む前に差分確認、クエスト変更は別チェック。\n地質学の使いどころを「裏チシキ」に追加。自動同期・録音の自動処理はまだありません。\n'+publicURL());
function recordForShare(id){const r=structuredClone(model.players[id]);for(const t of TASKS)r.done[t.id]=completion(t,id).done;return r;}
function encode(text){let s='';new TextEncoder().encode(text).forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function decode(text){if(text.length>20000)throw Error('共有データが長すぎます。');const s=text.replace(/-/g,'+').replace(/_/g,'/');const bin=atob(s+'='.repeat((4-s.length%4)%4));return new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(bin,c=>c.charCodeAt(0)));}
function sharePackage(ids){const dep=readDeparture();return{schema:SHARE,players:Object.fromEntries(ids.map(id=>[id,recordForShare(id)])),departure:{quest:dep.quest,players:Object.fromEntries(ids.map(id=>[id,dep.departure[id]]))}};}
$('share-flow').onclick=()=>{try{const person=who,payload=sharePackage([person]);showDialog('現在地と出発属性を共有','対象：'+person+'\n現在地・工程・出発属性の写しです。素材数・MR・録音は含みません。共通クエストは候補として含め、受け手が採用するか選びます。',()=>{const u=new URL(publicURL());u.searchParams.set('hunter',person);u.hash='flow='+encode(JSON.stringify(payload));copy(u.href);},'活動：'+ACTIVITY[payload.players[person].active]+'\n出発属性：'+ELEMENTS[payload.departure.players[person]]+'\nクエスト候補：'+QUESTS[payload.departure.quest]);}catch(error){say(error.message);}};
$('export').onclick=()=>{try{const out=sharePackage(PEOPLE.map(([id])=>id)),url=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='hunting-flow-v2.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);say('フローと出発属性を保存しました。素材台帳は別です。');}catch(error){say(error.message);}};
function propose(raw){const next=validate(raw),lines=[],beforeFlow=localStorage.getItem(KEY),beforeDeparture=localStorage.getItem(DKEY),dep=next.departure?readDeparture():null;
 for(const[id,r]of Object.entries(next.players)){const old=model.players[id];lines.push(id+'\n活動：'+ACTIVITY[old.active]+' → '+ACTIVITY[r.active]+'\n地学珠：'+String(old.geology)+' → '+String(r.geology)+'\n更新日時：'+(r.updatedAt||'不明')+(r.updatedAt&&old.updatedAt&&r.updatedAt<old.updatedAt?'（手元より古い可能性）':'')+'\n工程差分：'+Object.keys(r.done).filter(k=>r.done[k]!==completion(TASKS.find(t=>t.id===k),id).done).map(k=>TASKS.find(t=>t.id===k).title+'→'+(r.done[k]?'達成':'未確認')).join('、'));if(next.departure&&Object.hasOwn(next.departure.players,id))lines.push('出発属性：'+ELEMENTS[dep.departure[id]]+' → '+ELEMENTS[next.departure.players[id]]);}
 if(next.departure)lines.push('共有されたクエスト候補：'+QUESTS[next.departure.quest]+'（チェックしなければ手元を維持）');
 showDialog('持ち寄った記録を確認','記載された人だけを反映します。省略された工程・他の人・素材台帳・大目標の駒は維持。下の差分を確認してください。',()=>{try{
 if(localStorage.getItem(KEY)!==beforeFlow||localStorage.getItem(DKEY)!==beforeDeparture)throw Error('確認中に別の変更が入りました。もう一度取り込んで差分を確認してください。');
 const merged=structuredClone(model);for(const[id,r]of Object.entries(next.players))merged.players[id]={...r,done:{...model.players[id].done,...r.done}};
 if(dep){for(const[id,e]of Object.entries(next.departure.players))dep.departure[id]=e;if($('adopt-quest').checked)dep.quest=next.departure.quest;}
 const saved=writePair(merged,dep);undo={model:structuredClone(model)};if(dep){undo.departureRaw=saved.beforeDeparture;undo.departureAfter=localStorage.getItem(DKEY);}model=merged;blocked=false;notifyDeparture();render();say('確認した人の記録を取り込みました。');
 }catch(error){say(error.message);status();}},lines.join('\n\n'));
 if(next.departure){$('adopt-quest-label').hidden=false;$('adopt-quest').checked=false;}
}

$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>50000)throw Error('JSONは50KB以下にしてください。');propose(JSON.parse(await f.text()));}catch(err){say('取込できません：'+err.message);}finally{e.target.value='';}};
$('source-list').replaceChildren(...Object.entries(URLS).map(([key,url])=>{const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=({head:'通常ベリオ',legs:'オドガロン亜種',kirin:'キリン',teo:'MRテオ・フリー条件',armor:'鎧玉クエスト',jewels:'装飾品クエスト',frost:'氷刃ベリオ',geo:'地質学',alba:'アルバ任務',augment:'カスタム強化',safi:'ムフェト'})[key]+' ↗';return a;}));
window.addEventListener('storage',e=>{if([EKEY,PKEY,BKEY].includes(e.key)){readExternal();render();}else if(e.key===KEY&&e.newValue){try{const newer=validate(JSON.parse(e.newValue));Object.assign(model.players,newer.players);render();}catch{say('別タブのフローが不正なため読み込みませんでした。');}}});
window.addEventListener('focus',()=>{if($('dialog').open||document.activeElement?.matches('input,select,textarea'))return;readExternal();render();});window.addEventListener('resize',drawLines);if(window.ResizeObserver)new ResizeObserver(drawLines).observe($('chart'));
render();try{if(location.hash.startsWith('#flow=')){propose(JSON.parse(decode(location.hash.slice(6))));history.replaceState(null,'',location.pathname+location.search);}}catch(err){say('共有データを取り込めません：'+err.message);}
})();
