/* Discovery content. Original glossary and original illustration library are preserved. */
(()=>{'use strict';
const D=window.HUNTING_DICTIONARY,V=window.MH_VISUALS;if(!D||!V)return;
const sources={
t_flash:{label:'GameSpot｜Iceborne実プレイTips：MRの閃光耐性',url:'https://www.gamespot.com/gallery/monster-hunter-world-iceborne-tips-guide-clutch-cl/2900-3013/',note:'2019年の実プレイ記事。MRの閃光耐性・移動・休息の観察を参照。旧傷つけ説明は採用しない。'},
t_wound:{label:'ふぐおん｜Ver15.01の傷つけ・クラッチ攻撃強化を調査',url:'https://mhw.fuguai-online.com/2020/10/12/kuratti-sakugeki-08/'},
t_capacity:{label:'攻略レシピ｜スリンガー装填数UP',url:'https://mhwg.org/ida/1302.html'},
t_capacity2:{label:'GameWith｜スリンガー装填数UP・ぶっ飛ばし後の弾',url:'https://gamewith.jp/mhw/87932'},
t_oldtips:{label:'ふぐおん｜実戦・アイテム欄の小ネタ（2019）',url:'https://mhw.fuguai-online.com/2019/09/22/koneta/'},
t_geology:{label:'ほたてのたまりば｜導きの地で落とし物を2回拾う検証',url:'https://hotate24.hatenablog.jp/entry/2019/10/03/020624'},
t_geology2:{label:'MHW選民｜導きの地・地質学の対象と例外',url:'https://w.atwiki.jp/mhwyumi/pages/317.html'},
t_radial:{label:'攻略の虎｜実プレイ：ショートカットと自動調合',url:'https://monsterhunter.jp/world/guide/short.php'},
t_options:{label:'自分用攻略メモ｜Iceborneのオプション画面と設定',url:'https://mhw.tenju.work/mhwib-option-setting/',note:'PS4表記の画面例。PC・入力機器でボタン表記は異なる。'},
t_mantle:{label:'MHW選民｜装衣の再使用時間',url:'https://w.atwiki.jp/mhwyumi/pages/191.html'},
t_temporal:{label:'モンハン攻略・初心者講座｜転身・不動の対象攻撃',url:'https://bassy-mh.info/mhw-sougu.html',note:'World期の解説。装衣の旧効果時間は引用せず、被弾判定の違いのみ参照。'},
t_rajang:{label:'モンハン攻略戦記｜通常ラージャンの状態・罠・拘束対策',url:'https://www.monhan-senki.com/entry/mhwi-ra-zyan-point',note:'通常のラージャンの説明。激昂したラージャンにはそのまま適用しない。'},
t_zsd:{label:'モンハン攻略戦記｜零距離解放を実際に試した解説',url:'https://www.monhan-senki.com/entry/mhwi-switchaxe-panpan',note:'2019年記事。耳栓・派生動作を参照。傷90秒や当時の装備推奨は現行の結論として採用しない。'},
t_sa:{label:'攻略レシピ｜Iceborne追加スラアクアクション',url:'https://mhwg.org/data/3718.html'},
t_sleep:{label:'皆で一緒にモンハンライフ｜睡眠初撃・爆弾の設置検証',url:'https://a-to-monhan.com/2018/02/19/mhw-suiminboma/'},
t_powder:{label:'自分用攻略メモ｜大粉塵の回復・所持・調合を確認',url:'https://mhw.tenju.work/seimeino-daihunjin/'},
t_slinger:{label:'攻略の虎｜ゲーム内ロードTips：スリンガー',url:'https://monsterhunter.jp/world/guide/tips.php'},
t_environment:{label:'ふぐおん｜画面付き環境ギミックの観察（2023）',url:'https://mhw.fuguai-online.com/2023/12/30/koneta-2/'}
};
const entries=[];
function add(id,title,quick,cue,action,caution,scope,category,sources,steps,aliases,edition='iceborne',weapons=[],related=[],route='',icon='clutch-flinch'){
entries.push({id,title,reading:'',quick,cue,action,caution,scope,category,sources,steps,aliases,edition,weapons,related,route,icon,kind:'Tips',first:false,discovery:true,reviewed:'2026-09-20'});
}
add('flash-resistance-mr','閃光で、2回目は落ちない？','MRの閃光は連発で耐性。時間を空ける。','さっき落とせたのに、今度は空中に残る。','落下しないからと連射せず、別の隙を待つ。MRでは時間経過で耐性が回復する。','「1クエストに永久に1回」ではない。相手の例外や、上位歴戦の回数制限とは区別。','MR／閃光が有効な相手','効かない理由',['t_flash'],['まず落下','連発で耐性','時間で回復'],['閃光玉','閃光弾','閃光効かない','閃光 効かない','2回目','落ちない','飛んだまま','耐性','クールタイム'],'iceborne',[],['brightmoss-air','clutch-flinch'],'','enrage');
add('wound-duration-180','傷は、90秒ではなく180秒','Ver15.01で延長。削撃珠の効果とは別。','古い攻略動画の「90秒ごとに傷つけ」が気になる。','基本の傷持続は180秒として組み立て、切れた部位を更新する。','削撃珠を付けたから時間が延びるわけではない。古い資料の数字に注意。','IB／Ver15.01以降','クラッチ・武器',['t_wound'],['旧90秒','更新後180秒','珠とは別'],['傷つけ','傷時間','90秒','180秒','3分','傷すぐ消える'],'iceborne',[],['clutch-boost','clutch-flinch']);
add('clutch-boost','弓も、1回で傷をつけられる','クラッチ攻撃強化で、2回組の手間が変わる。','毎回2回しがみついて、傷つけに時間がかかる。','削撃珠などでクラッチ攻撃強化を発動する。通常の2回組も、傷つけ攻撃を完遂すれば1回で傷がつく。','しがみつくだけでは傷にならない。元から1回組は弾を落とす効果が加わる。','IB／スキル発動時','クラッチ・武器',['t_wound'],['従来2回','クラッチ攻撃強化','1回で傷'],['削撃珠','クラッチ攻撃強化','傷つけ2回','弓傷つけ','太刀傷つけ','軽量武器'],'iceborne',[],['wound-duration-180','sns-uppercut-wound'],'','bow-cs');
add('slinger-ammo-retain','壁ドン後も、弾を残せる','スリンガー装填数UPの増加分が残る。','壁ドンのたびに石ころを拾いに走っている。','石ころならLv1で増量できる。増加分を残し、拾い直さず次のぶっ飛ばしを狙う。','対応する弾の種類と必要Lvが違う。弾があっても、怒り中は通常の壁ドン不可。','IB／更新後のぶっ飛ばし','クラッチ・武器',['t_capacity','t_capacity2'],['増量して拾う','壁ドン','増加分が残る'],['スリンガー装填数UP','石ころ','壁ドン2回','ぶっ飛ばし2回','弾がなくなる','投石珠'],'iceborne',[],['rage-eye-wallbang'],'','sa-gauges');
add('rage-eye-wallbang','壁ドンが効くか、目を見る','ミニマップの目が赤なら、怒り中。','同じ操作なのに、方向転換やぶっ飛ばしに失敗する。','黄色の目を通常のぶっ飛ばしの目安にする。赤い間は、傷つけや攻撃の隙を選ぶ。','黄色でも地形・対象などの条件は必要。「必ず成功」の表示ではない。','IB／通常のぶっ飛ばし','効かない理由',['t_oldtips'],['黄：非怒り','赤：怒り','行動を切替'],['壁ドンできない','ぶっ飛ばない','怒りわからない','目の色','赤い目','黄色い目','挑戦者'],'iceborne',[],['enrage','slinger-ammo-retain'],'','enrage');
add('guiding-geologist','地質学Lv1で、落とし物をもう一度','導きの対象の落とし物は、2回拾える。','地質学は採掘用だと思って、狩猟装備から外していた。','導き素材集めの装備にLv1を試す。対象の落とし物は、1回拾った後ももう一度調べる。','全落とし物ではない。対象外のモンスターや、ぶんどり由来などの例外がある。','IB／導きの地・対象の落とし物','導き・探索',['t_geology','t_geology2'],['地質学Lv1','落とし物を拾う','対象ならもう1回'],['地学珠','地質学','落とし物2回','素材2倍','導き素材','骨','拾い直し'],'iceborne',[],['guiding-goal','slinger-ammo-retain'],'','capture');
add('guiding-goal','導きの募集目標は、現地で変えられる','出現を見てから、受付嬢で目的を設定。','入ってみたら、募集したい相手が変わった。','キャンプの受付嬢で探索の目的を設定し直してから、救難の募集を出す。','募集の目標変更。モンスターを呼び出す機能ではない。','IB／導きの地','導き・探索',['t_oldtips'],['現地の相手を見る','目的を変更','募集する'],['救難','募集目標','導き目的','探索目標','受付嬢','目標変更'],'iceborne',[],['guiding-geologist'],'導きの地 → キャンプの受付嬢 → 探索の目的','capture');
add('radial-loadout','ショートカットが、勝手に戻る','アイテムマイセットに、設定も保存されている。','直したはずの配置が、補充したら元通り。','設定後にマイセットも再登録する。IBでは「ショートカットのマイセット連動」をOFFにもできる。','連動OFFは、武器別の配置も自動で切り替えなくなる。','World共通／連動OFFはIB','設定の奥',['t_radial','t_options'],['配置を編集','古いマイセット読込','配置も戻る'],['ショトカ戻る','ショートカット戻る','設定消えた','マイセット','補充','登録したのに'],'iceborne',[],['radial-zero-craft','radial-click'],'オプション → GAME SETTING → ショートカットのマイセット連動','sa-gauges');
add('radial-zero-craft','0個の秘薬も、ショトカから調合','材料があれば、調合リストを開かなくていい。','秘薬が切れ、戦闘中にメニューを探してしまう。','アイテムをショートカットに登録し、調合素材も持つ。0個の登録枠を選ぶと調合できる。','調合と使用は同じではない。生成された後の個数と使用を確認。','World共通／材料を所持','マルチ・準備',['t_radial'],['登録枠は0個でも残る','材料から調合','作った物を使う'],['秘薬なくなった','秘薬0','自動調合','ショトカ調合','材料持ち','メニュー開かない'],'world',[],['lifepowder-six','craft-all','radial-loadout'],'','capture');
add('radial-click','秘薬のつもりが、砥石になる','ショトカは「押し込みで決定」に変えられる。','右スティックを戻すときに、隣の道具を誤使用する。','コントローラーのショートカット操作設定をタイプ2にすると、選択後の押し込みで発動。','入力が1つ増える。タイプ1に慣れているなら、必ず変更する必要はない。','World共通／コントローラー','設定の奥',['t_options'],['方向で選ぶ','押し込んで決定','戻すだけでは発動しない'],['ショトカ暴発','秘薬砥石','タイプ2','R3','誤操作','勝手に研ぐ'],'world',[],['radial-loadout'],'オプション → CONTROLS → ショートカット操作設定','evade-skills');
add('hide-fixed-tools','肉焼き機を、アイテム欄から隠す','売れない固定道具も、表示は減らせる。','回復薬を探すたび、使わない道具を通過する。','アイテムポーチで固定道具を選び、表示切替を使う。PS4表記では□。','隠した道具はショートカットに残すなど、使う入口を確保しておく。','IB／固定道具の表示切替','設定の奥',['t_oldtips'],['ポーチで選ぶ','表示をOFF','必要な物はショトカへ'],['肉焼き機','釣り竿','捕獲用ネット','観察キット','アイテム欄邪魔','非表示'],'iceborne',[],['radial-loadout'],'メニュー → アイテムポーチ → 道具を選択 → 表示切替','sharpness');
add('player-silhouette','腹の下で、自分が見えない','ハンターをシルエット表示できる。','大きい相手の陰で、位置や向きが分からない。','「プレイヤーの透過表示」をONにし、見やすい濃さにする。','当たり判定の表示ではない。相手の攻撃範囲まで見えるわけではない。','IB／画面表示設定','設定の奥',['t_options'],['相手の陰に入る','透過表示をON','自分の輪郭が見える'],['自分見えない','腹の下','透過','シルエット','ハンター隠れる'],'iceborne',[],['iframe'],'オプション → GAME SETTING → プレイヤーの透過表示','iframe');
add('mantle-cooldown','切れた装衣は、脱いで再使用待ち','着たままだと、待ち時間が始まらない。','装衣がボロボロなのに、なかなか復活しない。','効果が切れたら、安全な隙にアイテム欄やショートカットから手動で脱ぐ。','効果終了と取り外しは別。装備スロットの入れ替えにも注意。','World共通／装衣','マルチ・準備',['t_mantle','t_zsd'],['効果終了','手動で脱ぐ','再使用待ち開始'],['装衣復活しない','転身クールタイム','不動クールタイム','整備','ボロボロ','着っぱなし'],'world',[],['temporal-gaps','rocksteady-multihit'],'','stamina');
add('temporal-gaps','転身なのに、ダメージを受ける','小さなのけぞり攻撃や継続ダメージは別。','転身を着れば、全部自動で避けると思っていた。','発動条件はダメージ量の大小だけではない。削りや継続ダメージには自分で離れる。','転身は完全無敵ではない。耐久時間の古い解説と現行の仕様を混同しない。','World共通／転身の装衣','効かない理由',['t_temporal'],['大きい被弾は回避','小さな攻撃・削り','手動で離れる'],['転身効かない','転身死ぬ','スリップダメージ','小ダメージ','削り'],'world',[],['mantle-cooldown','rocksteady-multihit'],'','iframe');
add('rocksteady-multihit','不動が、連続被弾を招くことも','吹き飛ばされない分、その場で食らい続ける。','不動で張りついた瞬間、体力が一気に消える。','多段攻撃や持続判定に不動で居座らない。零距離でも体力と相手の次の動きを見る。','ダメージ軽減は無敵ではない。回復カスタムがあっても安全保証にはならない。','World共通／不動の装衣','効かない理由',['t_rajang','t_temporal'],['のけぞらない','同じ場所で連続被弾','危険なら離脱'],['不動死ぬ','不動即死','多段ヒット','パンパン死ぬ','クラッチ即死'],'world',[],['temporal-gaps','zsd-clutch'],'','gs-tackle');
add('rajang-trap-states','ラージャンの罠は、状態で替える','黒毛に落とし穴、赤い腕にシビレ罠は通らない。','罠を置いたのに、普通に踏み越えられる。','通常はシビレ罠、怒り時は落とし穴を候補にする。赤い腕の闘気硬化中はシビレ罠を避ける。','通常ラージャンの仕様。「金毛なら全部シビレ罠無効」ではない。激昂個体は別。','IB／通常ラージャン','効かない理由',['t_rajang'],['黒毛：穴×','赤い腕：シビレ×','状態を見て選ぶ'],['ラージャン罠','落とし穴効かない','シビレ罠効かない','闘気硬化','金毛','黒毛'],'iceborne',[],['rajang-tail','capture'],'','capture');
add('rajang-tail','赤い腕を解除したいなら、尻尾','通常ラージャンは、尻尾への蓄積で闘気硬化を解除。','赤く硬い腕に弾かれ、攻撃する場所がない。','後ろへ回ったら、後脚だけでなく尻尾を狙う。解除で攻める状況を変えられる。','尻尾がない激昂したラージャンには適用しない。切断するという意味でもない。','IB／通常ラージャン・闘気硬化','クラッチ・武器',['t_rajang'],['腕が硬化','尻尾へ蓄積','硬化を解除'],['ラージャン赤い腕','ラージャン尻尾','硬化解除','腕弾かれる'],'iceborne',[],['rajang-trap-states','hitzone'],'','flinch');
add('pin-slinger','掴まれて倒されても、撃てる場面がある','ラージャンの拘束後は、スリンガーで割り込める。','地面で動けず、追撃を待つだけになってしまう。','拘束後に射撃可能な場面では、はじけクルミなど怯ませやすい弾で追撃を止める。','すべての拘束で有効とは限らない。普通の石ころで同じ妨害を期待しない。','IB／通常ラージャンの拘束後など','マルチ・準備',['t_rajang'],['拘束で転倒','撃てる間に怯み弾','追撃を止める'],['拘束抜け','掴み','ラージャン起き攻め','動けない','スリンガー救助','はじけクルミ'],'iceborne',[],['lifepowder-six','rajang-trap-states'],'','emergency-dive');
add('zsd-earplugs','零距離中は、耳栓Lv1が効く','技の耳栓効果にLv1を足すと、Lv5相当。','咆哮で零距離を中断されるのを減らしたい。','耳栓Lv1を入れると、零距離解放中の耐性を補える。常時Lv5まで積むのとは別の考え方。','零距離解放中の話。通常攻撃中や、張りつく途中まで常時無効にはならない。','IB／スラアク・零距離解放中','クラッチ・武器',['t_zsd'],['技に耳栓効果','装備でLv1追加','技中はLv5相当'],['耳栓1','耳栓4','耳栓5','防音珠','パンパン咆哮','零距離咆哮'],'iceborne',['sa'],['zsd-clutch','sa-zsd'],'','sa-zsd');
add('zsd-clutch','高出力なら、クラッチから直接零距離','地上の突きを当てる手順を省ける。','張りつきたい部位に、属性解放突きが届かない。','高出力状態で狙った部位にクラッチし、零距離解放突きへ派生する。','零距離解放と、傷をつけるクラッチ武器攻撃は別。傷更新を兼ねると思わない。','IB／スラアク・高出力中','クラッチ・武器',['t_zsd','t_sa'],['高出力','狙う部位へクラッチ','直接零距離'],['パンパンゼミ','クラッチ零距離','零距離派生','ZSD','パンパン傷つかない'],'iceborne',['sa'],['zsd-earplugs','rocksteady-multihit','sa-zsd'],'','sa-zsd');
add('power-axe-flinch','斧強化は、怯ませる力が変わる','剣の高出力だけが、スラアクの強化ではない。','剣にする前の、ただの待ち時間だと思っていた。','斧の振り回しから強化叩きつけへつなぐと斧強化。部位を怯ませる目的でも選べる。','剣の覚醒ゲージや、高出力状態とは別の強化。','IB／スラアク・斧強化','クラッチ・武器',['t_sa'],['振り回し','強化叩きつけ','斧で怯ませやすく'],['斧強化','強化叩きつけ','パワーアックス','斧強化意味','ひるみ'],'iceborne',['sa'],['flinch','sa-gauges'],'','sa-gauges');
add('sns-uppercut-wound','片手剣は、アッパー込みで1回の傷','クローアッパーにも、傷の蓄積がある。','削撃珠なしだと、必ず2回張りつくと思っていた。','クローアッパーから張りつき、武器攻撃までつなげる。普通のクラッチ発射とは違う。','アッパーで張りついただけで、毎回傷が完成するわけではない。','IB／調整後の片手剣','クラッチ・武器',['t_wound'],['クローアッパー','クラッチ武器攻撃','傷が完成'],['片手剣傷つけ','アッパー','クラッチクローアッパー','削撃なし'],'iceborne',['sns'],['clutch-boost','wound-duration-180'],'','cb-gp');
add('sleep-first-hit','睡眠の2倍は、最初の1発だけ','爆弾全部や、コンボ全部が2倍にはならない。','みんなで同時に殴れば、全部強くなると思っていた。','起こす役と一撃を決める。起爆用の小さな攻撃が先に本体へ当たらないようにする。','1コンボではなく最初のダメージ判定。起爆の位置や攻撃順で結果が変わる。','World共通／通常の睡眠初撃','マルチ・準備',['t_sleep'],['睡眠','最初のダメージ×2','後続は通常'],['睡眠爆破','寝起きドッキリ','睡眠2倍','爆弾全部','初撃','誰が起こす','睡眠ボマー'],'world',[],['monster-rest-distance','gs-overcharge'],'','gs-overcharge');
add('lifepowder-six','大粉塵は、調合込みで6回分','完成品2個＋素材4組を持ち込める。','持てる2個を使い切ると、救助手段が尽きる。','生命の大粉塵2個に、不死虫と落陽草の花を各4個添える。使ったら補充調合する。','不死虫は他の調合でも使う。6回分は材料を残している場合。','IB／生命の大粉塵・材料込み','マルチ・準備',['t_powder'],['完成品2','花＋不死虫を各4','合計6回分'],['生命の大粉塵','大粉塵6','粉塵足りない','味方回復','落陽草の花','不死虫','救助'],'iceborne',[],['radial-zero-craft','craft-all','pin-slinger'],'','capture');
add('craft-all','調合ショトカは、1個ずつ以外も選べる','IBでは「すべて調合」を登録できる。','弾や粉塵を戻すために、何度も入力している。','調合のショートカット登録時に作成数を選ぶ。補充をまとめたい物には「すべて」を使う。','素材を他の物にも使うなら、一括消費に注意。所持上限は増えない。','IB／調合用ショートカット','設定の奥',['t_powder'],['調合を登録','作成数を「すべて」','まとめて補充'],['すべて調合','一括調合','弾調合連打','粉塵調合','まとめて作る'],'iceborne',[],['radial-zero-craft','lifepowder-six'],'ショートカット登録 → 調合する項目 → 一度に調合する数','sa-gauges');
add('brightmoss-air','ヒカリゴケは、照明だけではない','飛行中の頭に当てて、落とせる相手がいる。','閃光以外に、空から降ろす手段がない。','対応する飛竜には、頭部を狙うヒカリゴケも選択肢。地面を光らせる弾だけではない。','全飛行モンスターに一律有効ではない。必要命中数はこの版では断定しない。','World共通／対応する飛竜の飛行中','環境利用',['t_slinger'],['ヒカリゴケ','飛行中の頭を狙う','対応相手を落下'],['ヒカリゴケ','閃光以外','飛行対策','空中撃墜','光る弾'],'world',[],['flash-resistance-mr'],'','bow-distance');
add('waterpods-mud','水流弾で、泥の装甲を落とす','武器属性を変えなくても、泥に水を使える。','ボルボロスなどの泥が硬くて、攻撃が通りにくい。','ミズタマリゴケ由来のスリンガー水流弾を、泥の付いた部位へ使う。','泥を落とす用途。すべての硬い部位を軟化する弾ではない。','World共通／泥をまとった部位','環境利用',['t_slinger'],['泥の部位','スリンガー水流弾','泥をはがす'],['ミズタマリゴケ','水流弾','泥落とす','ボルボロス硬い','泥装甲'],'world',[],['hitzone'],'','hitzone');
add('coral-wallrun','あのピンクの珊瑚、縮めると登れる','衝撃で、駆け上がれる地形になる。','陸珊瑚の飾りだと思って、横を通っていた。','北西のミズザメカイメンに小タル爆弾などで衝撃を与え、縮んだ後の壁を使う。','すべての珊瑚が対象ではない。近くで戦う場面向けの環境利用。','World共通／陸珊瑚の台地・北西','環境利用',['t_environment'],['ミズザメカイメン','衝撃で縮む','駆け上がれる'],['ピンクの珊瑚','ミズザメカイメン','壁走り','駆け上がり','珊瑚縮む'],'world',[],['brightmoss-air'],'','bow-cs');
add('torch-icicles','種火石で、つららの落下を起こす','凍て地の洞窟に、利用できる天井がある。','頭上のつららを、背景として見ていた。','対応する氷柱に種火石を当てると、継続的な落下が発生する。相手をその下へ誘う。','味方も当たる。ハンターは吹き飛び・氷やられに注意。','IB／渡りの凍て地・対応する洞窟','環境利用',['t_environment'],['天井の氷柱','種火石','氷柱が落下'],['種火石','つらら','氷柱','凍て地洞窟','落石','天井'],'iceborne',[],['waterpods-mud'],'','flinch');
add('hidden-vigorwasp-tree','湿地の木の中に、回復ミツムシ','壊せる木は、回復の予備になる。','大蟻塚の湿地で、回復の場所を探している。','湿地にある対応の木へ爆弾などを当てて壊すと、ミツムシが出てくる。','普通の木すべてではない。出典の画面で対象の形を確認。','World共通／大蟻塚の荒地・湿地','環境利用',['t_environment'],['湿地の特殊な木','衝撃で破壊','回復ミツムシ'],['ミツムシ','湿地の木','回復虫','大蟻塚回復','隠れた回復'],'world',[],['lifepowder-six'],'','capture');
add('raider-ride-items','追跡中の研ぎ・回復を、ライド中に','移動を任せながら、次の戦闘の準備ができる。','相手が移動するたび、追うか研ぐかで迷う。','ライドコールで移動しながら、砥石や回復を使う。目的地は生態マップで指定できる。','利用には地域のライド解放が必要。自分で自由に操縦する乗り物ではない。','IB／ライド解放済みの地域','導き・探索',['t_flash'],['目的地を指定','移動中に研ぎ・回復','準備して合流'],['ライド研ぐ','ライド回復','ライドコール','移動中アイテム','追いつけない'],'iceborne',[],['sharpness','radial-loadout'],'','emergency-dive');
add('monster-rest-distance','巣まで追いすぎると、寝てくれない','休眠を待つなら、いったん距離を置く。','脚を引きずって巣へ帰ったのに、いつまでも戦う。','すぐ密着して追撃せず、離れて休眠に入るのを待つ。寝たら初撃や捕獲の準備をする。','ここでの睡眠は巣での休息。睡眠属性で寝かせる仕組みとは別。','IB／巣へ戻って休眠する相手','導き・探索',['t_flash'],['巣へ退く','追いすぎず離れる','休眠を待つ'],['寝ない','巣で寝ない','足引きずる','追いかけすぎ','休眠','捕獲したい'],'iceborne',[],['sleep-first-hit','capture'],'','exhaustion');
const priority=new Set(['flash-resistance-mr','clutch-boost','guiding-geologist','radial-loadout','mantle-cooldown','lifepowder-six']);for(const e of entries)e.first=priority.has(e.id);
Object.assign(D.sources,sources);const ids=new Set(D.entries.map(e=>e.id));D.entries=[...entries.filter(e=>!ids.has(e.id)),...D.entries];D.version='0.3.0';
const tips=new Map(entries.map(e=>[e.id,e])),oldIcon=V.icon.bind(V),oldPanels=V.panels.bind(V);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
for(const e of entries)V.map[e.id]={short:e.quick,warning:e.caution,scenes:[]};
V.icon=id=>tips.has(id)?oldIcon(tips.get(id).icon):oldIcon(id);
V.panels=id=>{const e=tips.get(id);if(!e)return oldPanels(id);return '<div class="tip-diagram"><ol class="tip-stages">'+e.steps.map((s,i)=>'<li><span class="tip-number">'+(i+1)+'</span><strong>'+esc(s)+'</strong></li>').join('')+'</ol></div>';};
const style=document.createElement('style');style.textContent=`.toolbar{flex-wrap:wrap}#entry-mode{min-height:42px;background:transparent;color:#eee9d5;border:1px solid #697a6c;padding:7px 23px 7px 11px;font-size:12px;max-width:155px}#entry-mode option{color:#263e38;background:#f4f0e4}.tip-scope{font-size:11px;color:#5b6d5e;margin:-9px 0 12px}.tip-route{font-size:12px;line-height:1.9;border-left:3px solid #b88336;padding:8px 12px;margin:0 0 16px;overflow-wrap:anywhere}.tip-diagram{grid-column:1/-1;padding:18px 12px}.tip-stages{list-style:none;padding:0;margin:0;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.tip-stages li{position:relative;text-align:center;display:flex;flex-direction:column;align-items:center;gap:13px;min-width:0}.tip-stages li+li:before{content:'→';position:absolute;left:-17px;top:5px;color:#9a763e}.tip-number{display:grid;place-items:center;border:1px solid #b3bda5;border-radius:50%;width:35px;height:35px;font:18px var(--serif);color:#667451}.tip-stages li:last-child .tip-number{background:#263e38;color:#f4f0e4;border-color:#263e38}.tip-stages strong{font-size:15px;line-height:1.85;font-weight:600;overflow-wrap:anywhere}.entry-name{overflow-wrap:anywhere}@media(max-width:850px){#entry-mode{font-size:11px;min-height:40px;max-width:132px}.tip-diagram{padding:14px 9px}.tip-stages{gap:14px}.tip-stages strong{font-size:12px}.tip-number{width:29px;height:29px;font-size:15px}.tip-stages li+li:before{left:-12px;top:1px}.tip-route{font-size:11px}.tip-scope{font-size:10px}.toolbar .result-count{white-space:nowrap}.entryhead h2{overflow-wrap:anywhere}}`;
document.head.append(style);
})();
