'use strict';
// Recipes are shared; inventory and requests are always hunter-specific.
window.HUNT_DATA = {
  version: '0.1.0', checked: '2026-09-20',
  sources: [
    {id:'bow-video', name:'弓装備の参考動画', url:'https://www.youtube.com/watch?v=019IDVQJDRw', note:'タイトル・武器種を確認。動画内の全構成は未転記。'},
    {id:'gs-video', name:'大剣装備の参考動画', url:'https://www.youtube.com/watch?v=pR-eVGPCmQw', note:'序盤〜終盤・クリア後の装備。動画内の全構成は未転記。'},
    {id:'sa-video', name:'スラアクの使い方・立ち回り', url:'https://www.youtube.com/watch?v=yuFl3NW4wTw', note:'操作解説。完成装備の根拠と混同しない。'}
  ],
  items: [
    {id:'lightbreak-axe', name:'砕光の剣斧', cat:'武器', type:'スラッシュアックス', tag:'爆破',
      note:'スラアクの強めの一本。まずはこの剣斧を作りたい。',
      detail:'攻撃力1050・爆破270・会心0%・強撃ビン。直接生産。必要費用は添付ゲーム画面の80,000zを採用。外部DBには40,000z表記があり、画面を優先。',
      price:80000, base:null, target:'臨界ブラキディオス',
      mats:[['砕竜の撃滅拳',3,'臨界ブラキディオス'],['砕竜の弾頭殻',1,'臨界ブラキディオス'],['不壊の黒曜甲',4,'臨界ブラキディオス'],['不滅の炉心殻',1,'臨界ブラキディオス']],
      source:'https://mhw.poedb.tw/jpn/weapon/Lightbreak%20Axe', evidence:'2026/09/20 添付ゲーム画面。所持数は撮影時点の記録。臨界ブラキ＝猛り爆ぜるブラキディオス。'},
    {id:'fire-bow', name:'蛮顎竜ノ火矢Ⅱ', cat:'武器', type:'弓', tag:'火', note:'火属性の弓を一本。',
      detail:'最終強化1段分。途中の派生・素材は含まない。', price:32000, base:'蛮顎竜ノ火矢Ⅰ',
      mats:[['蒼火竜の重殻',2,'リオレウス亜種'],['蛮顎竜の厚毛皮',3,'アンジャナフ'],['蛮顎竜の重鼻骨',2,'アンジャナフ'],['蛮顎竜の靭尾',1,'アンジャナフ']],
      source:'https://mhw.poedb.tw/jpn/weapon/Anjanath%20Flamebow%20II', video:'bow-video'},
    {id:'water-bow', name:'ラグーナシュートⅡ', cat:'武器', type:'弓', tag:'水', note:'水属性の弓を一本。',
      detail:'最終強化1段分。最終武器はプケプケ亜種系。参考画像字幕の「ジュラトドス」と区別する。', price:32000, base:'ラグーナシュートⅠ',
      mats:[['硫斬竜の重牙',2,'ディノバルド亜種'],['剛竜骨',3,'素材の入手先を確認'],['水妖鳥の特大喉袋',1,'プケプケ亜種'],['水妖鳥の靭尾',1,'プケプケ亜種']],
      source:'https://mhw.poedb.tw/jpn/weapon/Laguna%20Shot%20II', video:'bow-video'},
    {id:'thunder-bow', name:'万雷弓【羽々矢】', cat:'武器', type:'弓', tag:'雷', note:'雷属性の弓を一本。',
      detail:'最終強化1段分。途中の派生・素材は含まない。', price:24000, base:'飛雷弓【羽々矢】改',
      mats:[['惨爪竜の強硬筋',2,'オドガロン'],['飛雷竜の雷光針',2,'トビカガチ'],['飛雷竜の剛爪',2,'トビカガチ'],['飛雷竜の厚皮膜',2,'トビカガチ']],
      source:'https://mhw.poedb.tw/jpn/weapon/Thundering%20Strikebow', video:'bow-video'},
    {id:'ice-bow', name:'エーデルエスタ', cat:'武器', type:'弓', tag:'氷', note:'氷属性の弓を一本。',
      detail:'ここでは既存武器からの強化ルートを掲載。別途、直接生産ルートもある。両ルートの素材を合算しない。', price:40000, base:'アイシクルブリザードⅠ',
      mats:[['氷牙竜チケット',2,'氷刃佩くベリオロス'],['白銀の氷刃牙',3,'氷刃佩くベリオロス'],['氷河を砕く剣爪',1,'氷刃佩くベリオロス'],['グラシスメタル',5,'渡りの凍て地で採掘']],
      source:'https://mhw.poedb.tw/jpn/weapon/Edelescha', video:'bow-video'},
    {id:'mighty-bow', name:'強弓珠【2】を手に入れる', cat:'珠・護石', type:'弓', tag:'マカ錬金', note:'4属性の弓と一緒に、強弓珠も用意する。',
      detail:'調査ポイント6,000と錬金値4,000は別勘定。錬金値は投入する装飾品の合計評価値で、珠の個数ではない。必要な珠は消費しない。解放・所持はゲーム内で確認。',
      price:null, mats:[['調査ポイント',6000,'マカ錬金の準備','pts'],['投入できる錬金値',4000,'マカ錬金の準備','値']],
      source:'https://mhw.poedb.tw/jpn/elder_melder', video:'bow-video'},
    {id:'power-prolonger', name:'強化持続つきの防具', cat:'防具', type:'スラッシュアックス', tag:'組み合わせ相談',
      note:'強化を長持ちさせたい。今の防具と合わせて考える。',
      detail:'候補：EXジンオウヘルムαは強化持続Lv2＋超会心Lv1。EXディノメイルαは強化持続Lv2。EXデスガロングリーヴαは強化持続Lv1＋整備Lv2。いずれも候補で、採用部位・装飾品・完成セットは未確定。',
      target:'強化持続の防具を選ぶ', price:null, mats:[], source:'https://mhw.poedb.tw/jpn/skill/Power%20Prolonger', video:'sa-video'},
    {id:'greatsword-set', name:'大剣の装備を組む', cat:'防具', type:'大剣', tag:'組み合わせ相談',
      note:'大剣も使ってみたい。今の進行度で作る一式を決める。', detail:'参考動画を見ながら、武器・各部位・珠・護石を確定する。未確認のテンプレ装備は登録していない。',
      target:'大剣の装備を相談する', price:null, mats:[], video:'gs-video'},
    {id:'mantles', name:'装衣を揃える・改にする', cat:'装衣', type:'共通', tag:'解放を確認',
      note:'装衣各種。どれを持っていて、何から取るか相談したい。', detail:'対象の装衣名・所持・改への強化状況は未確認。「不動の装衣を改にする」など、決まったものから個別の依頼を追加する。煙筒は装衣とは別の特殊装具。',
      target:'装衣の所持と解放条件を確認', price:null, mats:[]},
    {id:'armor-spheres', name:'鎧玉を集めて防具を強化', cat:'素材', type:'共通', tag:'目標を決める',
      note:'鎧玉各種。装備を決めたら、防御力も上げておく。', detail:'鎧玉の種類・所持数・目標防具・強化段階を決めてから必要量を記録する。必要数はまだ算出していない。',
      target:'防具強化と鎧玉の在庫を確認', price:null, mats:[]},
    {id:'maintenance', name:'整備まわりを強化', cat:'珠・護石', type:'共通', tag:'方針を確認',
      note:'装衣をもっと回しやすくしたい。', detail:'整備珠そのものを強化するのではなく、装備・珠・護石で整備のスキルレベルを上げる。護石の強化を意図したかは未確定。',
      target:'整備の珠・護石を確認', price:null, mats:[], source:'https://mhw.poedb.tw/jpn/skill/Tool%20Specialist'}
  ]
};
